version: '2'
services:

  replica0:
    image: vr/replica
    env_file:
      - all.env
    environment:
      - REPLICA_NUMBER=0

  replica1:
    image: vr/replica
    env_file:
     - all.env
    environment:
     - REPLICA_NUMBER=1

  replica2:
    image: vr/replica
    env_file:
     - all.env
    environment:
     - REPLICA_NUMBER=2

  client:
    image: vr/client
    env_file:
      - all.env
    environment:
      - CLIENT_ID=client
      - OWN_ADDRESS=client:8000